---
- name: Wait for kubeconfig file after deploying Microshift
  become: true
  ansible.builtin.wait_for:
    path: /var/lib/microshift/resources/kubeadmin/{{ fqdn }}/kubeconfig
    search_regex: microshift
    delay: 5
    timeout: 300

- name: Create kube config directory
  ansible.builtin.file:
    path: ~/.kube
    state: directory
    mode: "0755"

- name: Copy kubeconfig for localhost
  become: true
  ansible.builtin.copy:
    src: /var/lib/microshift/resources/kubeadmin/kubeconfig
    dest: "{{ ansible_user_dir }}/.kube/config-localhost"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"

- name: "Copy kubeconfig for {{ fqdn }}"
  become: true
  ansible.builtin.copy:
    src: /var/lib/microshift/resources/kubeadmin/{{ fqdn }}/kubeconfig
    dest: "{{ ansible_user_dir }}/.kube/config"
    remote_src: true
    owner: "{{ ansible_user_id }}"
    group: "{{ ansible_user_id }}"
    mode: "0644"
